In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

from fairlearn.metrics import MetricFrame, selection_rate, true_positive_rate, false_positive_rate
from fairlearn.reductions import ExponentiatedGradient, DemographicParity
from fairlearn.postprocessing import ThresholdOptimizer

from sklearn.datasets import fetch_openml

In [6]:
# fetch_openml es una función que permite descargar datasets desde la plataforma OpenML.
# Dataset de clasificación binaria para predecir si una persona gana más o menos de $50,000 anuales
adult = fetch_openml(data_id=1590, as_frame=True) # as_frame = True devuelve los datos como un DataFrames de pandas
# adult = fetch_openml(name='adult', version='latest', as_frame=True)

X = adult.data
y = (adult.target == ">50K").astype(int)  # variable binaria ingresos altos

# Atributo sensible: sexo
sensitive_feature = X["sex"]

In [5]:
adult.frame.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K

En one-hot encoding podemos encontrarnos con el problema de no saber distinguir entre:
- Un dato faltante (NaN)
- La categoría que se deja fuera por colinealidad (drop_first=True)

Soluciones recomendadas:
1. Tratar los NaN como una catetoria aparte -> Usar dummy_na=True en pd.get_dummies
2. Reemplazar NaN por una categoría como "Unknown" o "Missing"
3. Eliminar filas con NaN si son pocas y no aportan información útil

In [27]:
# Preprocesado simple: eliminar columnas con strings complejos
X = pd.get_dummies(X.drop(columns=["sex", "race"]), drop_first=True)

In [ ]:
print(X.isna().sum().to_string()) #Lista el número de NaN en cada columna

age                                          0
fnlwgt                                       0
education-num                                0
capital-gain                                 0
capital-loss                                 0
hours-per-week                               0
workclass_Local-gov                          0
workclass_Never-worked                       0
workclass_Private                            0
workclass_Self-emp-inc                       0
workclass_Self-emp-not-inc                   0
workclass_State-gov                          0
workclass_Without-pay                        0
education_11th                               0
education_12th                               0
education_1st-4th                            0
education_5th-6th                            0
education_7th-8th                            0
education_9th                                0
education_Assoc-acdm                         0
education_Assoc-voc                          0
education_Bachelors                          0
education_Doctorate                          0
education_HS-grad                            0
education_Masters                            0
education_Preschool                          0
education_Prof-school                        0
education_Some-college                       0
marital-status_Married-AF-spouse             0
marital-status_Married-civ-spouse            0
marital-status_Married-spouse-absent         0
marital-status_Never-married                 0
marital-status_Separated                     0
marital-status_Widowed                       0
occupation_Armed-Forces                      0
occupation_Craft-repair                      0
occupation_Exec-managerial                   0
occupation_Farming-fishing                   0
occupation_Handlers-cleaners                 0
occupation_Machine-op-inspct                 0
occupation_Other-service                     0
occupation_Priv-house-serv                   0
occupation_Prof-specialty                    0
occupation_Protective-serv                   0
occupation_Sales                             0
occupation_Tech-support                      0
occupation_Transport-moving                  0
relationship_Not-in-family                   0
relationship_Other-relative                  0
relationship_Own-child                       0
relationship_Unmarried                       0
relationship_Wife                            0
native-country_Canada                        0
native-country_China                         0
native-country_Columbia                      0
native-country_Cuba                          0
native-country_Dominican-Republic            0
native-country_Ecuador                       0
native-country_El-Salvador                   0
native-country_England                       0
native-country_France                        0
native-country_Germany                       0
native-country_Greece                        0
native-country_Guatemala                     0
native-country_Haiti                         0
native-country_Holand-Netherlands            0
native-country_Honduras                      0
native-country_Hong                          0
native-country_Hungary                       0
native-country_India                         0
native-country_Iran                          0
native-country_Ireland                       0
native-country_Italy                         0
native-country_Jamaica                       0
native-country_Japan                         0
native-country_Laos                          0
native-country_Mexico                        0
native-country_Nicaragua                     0
native-country_Outlying-US(Guam-USVI-etc)    0
native-country_Peru                          0
native-country_Philippines                   0
native-country_Poland                        0
native-country_Portugal                      0
native-country_Puerto-Rico                   0
native-country_Scotland                      0
native-country_South                         0
native-country_Taiwan                        0
native-country_Thailand                      0
native-country_Trinadad&Tobago               0
native-country_United-States                 0
native-country_Vietnam                       0
native-country_Yugoslavia                    0

In [ ]:
X.columns[X.isna().any()] #Lista las columnas en las que hay algún NaN

Index([], dtype='object')

In [ ]:
X[X.isna().any(axis=1)] #Comprobamos si hay NaN en algun registro

Empty DataFrame
Columns: [age, fnlwgt, education-num, capital-gain, capital-loss, hours-per-week, workclass_Local-gov, workclass_Never-worked, workclass_Private, workclass_Self-emp-inc, workclass_Self-emp-not-inc, workclass_State-gov, workclass_Without-pay, education_11th, education_12th, education_1st-4th, education_5th-6th, education_7th-8th, education_9th, education_Assoc-acdm, education_Assoc-voc, education_Bachelors, education_Doctorate, education_HS-grad, education_Masters, education_Preschool, education_Prof-school, education_Some-college, marital-status_Married-AF-spouse, marital-status_Married-civ-spouse, marital-status_Married-spouse-absent, marital-status_Never-married, marital-status_Separated, marital-status_Widowed, occupation_Armed-Forces, occupation_Craft-repair, occupation_Exec-managerial, occupation_Farming-fishing, occupation_Handlers-cleaners, occupation_Machine-op-inspct, occupation_Other-service, occupation_Priv-house-serv, occupation_Prof-specialty, occupation_Protective-serv, occupation_Sales, occupation_Tech-support, occupation_Transport-moving, relationship_Not-in-family, relationship_Other-relative, relationship_Own-child, relationship_Unmarried, relationship_Wife, native-country_Canada, native-country_China, native-country_Columbia, native-country_Cuba, native-country_Dominican-Republic, native-country_Ecuador, native-country_El-Salvador, native-country_England, native-country_France, native-country_Germany, native-country_Greece, native-country_Guatemala, native-country_Haiti, native-country_Holand-Netherlands, native-country_Honduras, native-country_Hong, native-country_Hungary, native-country_India, native-country_Iran, native-country_Ireland, native-country_Italy, native-country_Jamaica, native-country_Japan, native-country_Laos, native-country_Mexico, native-country_Nicaragua, native-country_Outlying-US(Guam-USVI-etc), native-country_Peru, native-country_Philippines, native-country_Poland, native-country_Portugal, native-country_Puerto-Rico, native-country_Scotland, native-country_South, native-country_Taiwan, native-country_Thailand, native-country_Trinadad&Tobago, native-country_United-States, native-country_Vietnam, native-country_Yugoslavia]
Index: []

[0 rows x 92 columns]

In [28]:
# Split train/test
X_train, X_test, y_train, y_test, sex_train, sex_test = train_test_split(
    X, y, sensitive_feature, test_size=0.3, random_state=42, stratify=y
) #stratify mantiene las proporciones del dataset original dadas las variables de interés

In [ ]:
# Modelo base
scaler = StandardScaler() 
X_train_scaled = scaler.fit_transform(X_train) #Normalizamos datos, LogisticRegression es sensible a órdenes de magnitud
X_test_scaled = scaler.transform(X_test) #Obviamos el fit para evitar data leakage

clf = LogisticRegression(max_iter=200)
clf.fit(X_train_scaled, y_train)

y_pred = clf.predict(X_test_scaled)

print("Accuracy base:", accuracy_score(y_test, y_pred))

Accuracy base: 0.85415955776974

In [ ]:
# Métricas de equidad 
metrics = {
    "accuracy": accuracy_score,         #% de predicciones correctas
    "selection_rate": selection_rate,   #% de personas clasificadas como "ingresos altos"
    "TPR": true_positive_rate,          #% de personas con ingresos altos correctamente identificadas
    "FPR": false_positive_rate,         #% de personas con ingresos bajos incorrectamente clasificadas como "altos"
}

mf = MetricFrame(metrics=metrics, y_true=y_test, y_pred=y_pred, sensitive_features=sex_test)
print("\nMétricas por grupo (modelo base):")
print(mf.by_group)

Métricas por grupo (modelo base):
        accuracy  selection_rate       TPR       FPR
sex
Female  0.927733        0.079473  0.531646  0.021375
Male    0.817681        0.247346  0.607856  0.091773

In [ ]:
# Mitigación: In-Processing con fairness constraint
constraint = DemographicParity()
mitigator = ExponentiatedGradient(LogisticRegression(max_iter=200), constraint)
mitigator.fit(X_train_scaled, y_train, sensitive_features=sex_train) #Durante el entrenamiento considera tanto la precisión como la equidad

y_pred_fair = mitigator.predict(X_test_scaled)

mf_fair = MetricFrame(metrics=metrics, y_true=y_test, y_pred=y_pred_fair, sensitive_features=sex_test)
print("\nMétricas por grupo (mitigado - InProcessing):")
print(mf_fair.by_group)

Métricas por grupo (mitigado - InProcessing):
        accuracy  selection_rate       TPR       FPR
sex
Female  0.896026        0.151946  0.710669  0.080158
Male    0.802675        0.157820  0.434473  0.038433

**Trade-off**

Ganancia: Equidad perfecta (selection rate casi igual)

Pérdida: Ligera reducción en accuracy general

In [ ]:
# Mitigación: Post-Processing 
postproc = ThresholdOptimizer(estimator=clf, constraints="demographic_parity",
                             prefit=True)
postproc.fit(X_train_scaled, y_train, sensitive_features=sex_train)

y_pred_post = postproc.predict(X_test_scaled, sensitive_features=sex_test)

mf_post = MetricFrame(metrics=metrics, y_true=y_test, y_pred=y_pred_post, sensitive_features=sex_test)
print("\nMétricas por grupo (mitigado - PostProcessing):")
print(mf_post.by_group)

Métricas por grupo (mitigado - PostProcessing):
        accuracy  selection_rate       TPR       FPR
sex
Female  0.893556        0.165123  0.757685  0.088987
Male    0.801960        0.155063  0.428717  0.036972